name: Validar código Python

on:
  push:
    branches:
      - main
      - feature/validacion-automatica
  pull_request:
    branches:
      - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verificar sintaxis
        run: python -m py_compile app.py